"""
Catálogo inicial de productos.
Se importa en main.py para sembrar la base de datos en el primer arranque.
"""

SEED_PRODUCTS = [
    # ── PINTURAS VALENTINE ──────────────────────────────────────────────────
    {
        "id": "val-001",
        "nombre": "Valentine Valon Extramate - Pintura Plástica Mate 15L",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 34.95,
        "descripcion": "Pintura plástica vinílica mate de primera calidad para interior y exterior. Excelente cubrición, lavabilidad y resistencia. Blanco puro.",
        "imagen": "/img/productos/val-001.jpg",
        "stock": 150,
        "tags": ["interior", "exterior", "mate", "paredes"],
        "destacado": True,
        "referencia": "0120102379",
    },
    {
        "id": "val-002",
        "nombre": "Valentine Easy Plus - Pintura Plástica 15L",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 28.50,
        "descripcion": "Pintura de alta calidad para decoración interior. Fácil aplicación y excelente acabado.",
        "imagen": "/img/productos/val-002.jpg",
        "stock": 100,
        "tags": ["interior", "fácil", "decoración"],
        "destacado": True,
        "referencia": "VAL-EASY-15",
    },
    {
        "id": "val-003",
        "nombre": "Valentine R-30 - Pintura Plástica Mate Exterior 15L",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 42.00,
        "descripcion": "Pintura plástica mate para exterior de alta resistencia. Resiste intemperie y rayos UV.",
        "imagen": "/img/productos/val-003.jpg",
        "stock": 80,
        "tags": ["exterior", "resistente", "UV"],
        "destacado": True,
        "referencia": "VAL-R30-15",
    },
    {
        "id": "val-004",
        "nombre": "Valentine Esmalte Sintético Brillo 750ml",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 18.90,
        "descripcion": "Esmalte sintético de alto brillo para metales, maderas y PVC. Resistencia a la corrosión.",
        "imagen": "/img/productos/val-004.jpg",
        "stock": 60,
        "tags": ["esmalte", "metal", "brillo"],
        "destacado": False,
        "referencia": "VAL-ESM-075",
    },
    {
        "id": "val-005",
        "nombre": "Valentine Masilla Plástica 500ml",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 6.50,
        "descripcion": "Masilla acuosa para repaso y reparación de superficies. Secado rápido.",
        "imagen": "/img/productos/val-005.jpg",
        "stock": 200,
        "tags": ["masilla", "reparación"],
        "destacado": False,
        "referencia": "VAL-MAS-05",
    },
    {
        "id": "val-006",
        "nombre": "Valentine Imprimación Universal 5L",
        "marca": "Valentine",
        "categoria": "pinturas",
        "precio": 15.90,
        "descripcion": "Imprimación universal al agua para interior y exterior. Mejora adherencia.",
        "imagen": "/img/productos/val-006.jpg",
        "stock": 90,
        "tags": ["imprimación", "adherencia"],
        "destacado": False,
        "referencia": "VAL-PRIM-05",
    },

    # ── MORTEROS KERAKOLL ───────────────────────────────────────────────────
    {
        "id": "ker-001",
        "nombre": "Kerakoll H40 Gel Adhesivo Gris 20kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 28.90,
        "descripcion": "Gel-adhesivo estructural flexible multiuso para gres porcelánico, cerámica y piedra natural.",
        "imagen": "/img/productos/ker-001.jpg",
        "stock": 80,
        "tags": ["adhesivo", "cerámica", "flexible"],
        "destacado": True,
        "referencia": "KER-H40-GEL",
    },
    {
        "id": "ker-002",
        "nombre": "Kerakoll Rasante Hydro - Mortero Impermeable 25kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 32.00,
        "descripcion": "Mortero técnico impermeable para rehabilitación de muros húmedos.",
        "imagen": "/img/productos/ker-002.jpg",
        "stock": 50,
        "tags": ["impermeable", "rehabilitación", "humedad"],
        "destacado": True,
        "referencia": "KER-RAS-HYDRO",
    },
    {
        "id": "ker-003",
        "nombre": "Kerakoll Fugabella Eco - Lechada de Juntas 5kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 24.50,
        "descripcion": "Lechada de rejuntado híbrida de alta tecnología. Resistente a manchas y moho.",
        "imagen": "/img/productos/ker-003.jpg",
        "stock": 100,
        "tags": ["rejuntado", "cerámica", "baño"],
        "destacado": True,
        "referencia": "KER-FUG-ECO",
    },
    {
        "id": "ker-004",
        "nombre": "Kerakoll Keracem Premium - Mortero Técnico 25kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 38.00,
        "descripcion": "Mortero técnico de altas prestaciones para saneamientos y renovaciones.",
        "imagen": "/img/productos/ker-004.jpg",
        "stock": 35,
        "tags": ["técnico", "saneamiento"],
        "destacado": False,
        "referencia": "KER-KERACEM",
    },
    {
        "id": "ker-005",
        "nombre": "Kerakoll Biogel - Adhesivo Rápido 15kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 35.00,
        "descripcion": "Adhesivo reactivo de fraguado rápido para recolocación de azulejos.",
        "imagen": "/img/productos/ker-005.jpg",
        "stock": 40,
        "tags": ["rápido", "reparación"],
        "destacado": False,
        "referencia": "KER-BIOGEL",
    },
    {
        "id": "ker-006",
        "nombre": "Kerakoll Nivelante - Mortero Autonivelante 25kg",
        "marca": "Kerakoll",
        "categoria": "morteros",
        "precio": 28.00,
        "descripcion": "Mortero autonivelante de alta fluidez para suelos.",
        "imagen": "/img/productos/ker-006.jpg",
        "stock": 45,
        "tags": ["suelo", "nivelante"],
        "destacado": False,
        "referencia": "KER-NIVEL",
    },

    # ── IMPERMEABILIZANTES HIGALTOR ─────────────────────────────────────────
    {
        "id": "hig-001",
        "nombre": "Higaltor D-273 - Membrana Líquida 20L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 89.00,
        "descripcion": "Membrana líquida impermeabilizante de alta calidad para terrazas y cubiertas.",
        "imagen": "/img/productos/hig-001.jpg",
        "stock": 70,
        "tags": ["líquido", "cubiertas", "terrazas"],
        "destacado": True,
        "referencia": "HIG-D273",
    },
    {
        "id": "hig-002",
        "nombre": "Higaltor D-316 - Hidrofugante 5L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 45.00,
        "descripcion": "Hidrofugante de base acuosa para protección de fachadas y muros.",
        "imagen": "/img/productos/hig-002.jpg",
        "stock": 120,
        "tags": ["hidrofugante", "fachada"],
        "destacado": True,
        "referencia": "HIG-D316",
    },
    {
        "id": "hig-003",
        "nombre": "Higaltor D-332 - Consolidante Yesos 5L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 38.00,
        "descripcion": "Consolidante para yesos y escayolas. Mejora la adherencia.",
        "imagen": "/img/productos/hig-003.jpg",
        "stock": 60,
        "tags": ["consolidante", "yeso"],
        "destacado": False,
        "referencia": "HIG-D332",
    },
    {
        "id": "hig-004",
        "nombre": "Higaltor D-337 - Limpiador Eflorescencias 5L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 32.00,
        "descripcion": "Limpiador de eflorescencias y sales para fachadas de ladrillo y piedra.",
        "imagen": "/img/productos/hig-004.jpg",
        "stock": 55,
        "tags": ["limpiador", "sal", "fachada"],
        "destacado": False,
        "referencia": "HIG-D337",
    },
    {
        "id": "hig-005",
        "nombre": "Higaltor D-338 - Limpiador Anti Verdín 5L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 35.00,
        "descripcion": "Limpiador especializado anti moho y verdín para superficies exteriores.",
        "imagen": "/img/productos/hig-005.jpg",
        "stock": 65,
        "tags": ["anti verdín", "moho"],
        "destacado": False,
        "referencia": "HIG-D338",
    },
    {
        "id": "hig-006",
        "nombre": "Higaltor D-339 - Protección Anti-orines 5L",
        "marca": "Higaltor",
        "categoria": "impermeabilizantes",
        "precio": 42.00,
        "descripcion": "Protector antihumedad específico para zonas con exposición a orines.",
        "imagen": "/img/productos/hig-006.jpg",
        "stock": 40,
        "tags": ["protección", "anti-orines"],
        "destacado": False,
        "referencia": "HIG-D339",
    },

    # ── TRATAMIENTOS ANTIHUMEDAD ────────────────────────────────────────────
    {
        "id": "hum-001",
        "nombre": "Deshumidificador Profesional 20L/24h",
        "marca": "Varios",
        "categoria": "herramientas",
        "precio": 189.00,
        "descripcion": "Deshumidificador comercial de gran capacidad para eliminar humedad por condensación.",
        "imagen": "/img/productos/hum-001.jpg",
        "stock": 12,
        "tags": ["condensación", "equipo", "profesional"],
        "destacado": True,
        "referencia": None,
    },
    {
        "id": "hum-002",
        "nombre": "Ventilador Extractor axial 300mm",
        "marca": "Varios",
        "categoria": "herramientas",
        "precio": 89.00,
        "descripcion": "Ventilador extractor industrial para mejora de ventilación.",
        "imagen": "/img/productos/hum-002.jpg",
        "stock": 25,
        "tags": ["condensación", "ventilación"],
        "destacado": False,
        "referencia": None,
    },
    {
        "id": "hum-003",
        "nombre": "Sistema Inyección Sanosil - Anti Capilaridad",
        "marca": "Varios",
        "categoria": "tratamientos",
        "precio": 125.00,
        "descripcion": "Kit completo de inyección para tratamiento de humedad ascendente.",
        "imagen": "/img/productos/hum-003.jpg",
        "stock": 20,
        "tags": ["capilaridad", "tratamiento", "inyección"],
        "destacado": True,
        "referencia": None,
    },
    {
        "id": "hum-004",
        "nombre": "Lámina Barrier Antihumedad - Rollo 50m",
        "marca": "Varios",
        "categoria": "tratamientos",
        "precio": 65.00,
        "descripcion": "Lámina de polietileno para crear barrera antihumedad horizontal en muros.",
        "imagen": "/img/productos/hum-004.jpg",
        "stock": 50,
        "tags": ["capilaridad", "barrera"],
        "destacado": False,
        "referencia": None,
    },
    {
        "id": "hum-005",
        "nombre": "Sellador Poliuretano Profesional 300ml",
        "marca": "Varios",
        "categoria": "tratamientos",
        "precio": 12.00,
        "descripcion": "Sellador de poliuretano elástico para reparación de grietas y zonas con filtración.",
        "imagen": "/img/productos/hum-005.jpg",
        "stock": 100,
        "tags": ["filtración", "grietas", "sellado"],
        "destacado": False,
        "referencia": None,
    },
    {
        "id": "hum-006",
        "nombre": "Mortero Reparación Rápida 25kg",
        "marca": "Varios",
        "categoria": "morteros",
        "precio": 28.00,
        "descripcion": "Mortero técnico de reparación rápida para zonas con filtración.",
        "imagen": "/img/productos/hum-006.jpg",
        "stock": 35,
        "tags": ["filtración", "reparación", "rápido"],
        "destacado": False,
        "referencia": None,
    },
]

SEED_CATEGORIES = [
    {
        "id": "pinturas",
        "nombre": "Pinturas Valentine",
        "descripcion": "Pinturas para interior y exterior de la marca Valentine",
        "imagen": "/img/categorias/pinturas.jpg",
        "icono": "🎨",
    },
    {
        "id": "morteros",
        "nombre": "Morteros Kerakoll",
        "descripcion": "Morteros técnicos, adhesivos y colas Kerakoll",
        "imagen": "/img/categorias/morteros.jpg",
        "icono": "🧱",
    },
    {
        "id": "impermeabilizantes",
        "nombre": "Impermeabilizantes Higaltor",
        "descripcion": "Sistemas de impermeabilización Higaltor",
        "imagen": "/img/categorias/impermeabilizantes.jpg",
        "icono": "🌧️",
    },
    {
        "id": "tratamientos",
        "nombre": "Tratamientos Humedad",
        "descripcion": "Tratamientos específicos antihumedad",
        "imagen": "/img/categorias/tratamientos.jpg",
        "icono": "🛠️",
    },
    {
        "id": "herramientas",
        "nombre": "Herramientas",
        "descripcion": "Equipos y herramientas profesionales",
        "imagen": "/img/categorias/herramientas.jpg",
        "icono": "🔧",
    },
]

# Productos recomendados por tipo de humedad (para el análisis IA)
HUMIDITY_RECOMMENDATIONS = {
    "condensacion": ["hum-001", "hum-002", "val-001", "val-004", "hig-001"],
    "capilaridad": ["hum-003", "hum-004", "ker-002", "ker-003", "hig-002"],
    "filtracion": ["hum-005", "hum-006", "ker-004", "hig-003", "hig-004"],
}
